tunnelConfig:
  name: nostramo-tunnel
tunnelSecrets:
  existingConfigJsonFileSecret:
    name: config-json-file-secret
  existingPemFileSecret:
    name: cert-pem-file-secret
ingress:
  - hostname: grafana.nostramo.cloud
    service: http://traefik.kube-system.svc.cluster.local:80
  - service: http_status:404
