apiVersion: v1
kind: Namespace
metadata:
  name: victoria-metrics
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: victoria-metrics
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
spec:
  tls:
    - hosts:
        - grafana.nostramo.cloud
      secretName: grafana-tls-cert
  ingressClassName: traefik
  rules:
    - host: grafana.nostramo.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: victoria-metrics-stack-grafana
                port:
                  number: 80
