apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-config
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Kyleg142/nostramo-lab.git"
    path: infrastructure/victoria-metrics
  destination:
    server: https://kubernetes.default.svc
    namespace: victoria-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
